
spring.application.name=team-players
spring.config.import=optional:configserver:
server.port=4000
football-players.robbon.listOservers=htt://localhost:8888,htt://localhost:8888,htt://localhost:8888:8589