spring.application.name=players-statistics
players.statistics.numberTeams=2000
players.statistics.numberPlayers=20000
players.statistics.country=Caire
spring.cloud.config.uri=http://localhost:9090
spring.config.import=optional:configserver:
server.port=9092
!spring.profiles.active=